version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bulkflyergenerator-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: bulkflyergenerator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bulkflyergenerator"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local
